### ISSUE TITLE
没有yaml文件

### ISSUE THREAD

**Issue by dong200** [noviceswing/yolov5-mask#1]
您好，这边显示没有data\mask.yaml

**Comment by WangHaoyuuu** [comment]
您好，这里没有提供相关训练的文件，因为后续上传的时候没找到数据集，只保留了训练好的权重。   
```
# 数据集的根目录
path: ./datasets/mask-dataset  

# 训练数据集的路径
train: images/train  

# 验证数据集的路径
val: images/val  

# 类别数量
nc: 2  

# 类别名称
names: ['unmasked', 'masked']  
```  
可以试一下

**Comment by dong200** [comment]
好的好的，谢谢您


&nbsp;


通信1902董海阔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月24日(星期五) 上午9:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [noviceswing/yolov5-mask] 没有yaml文件 (Issue #1)





 
您好，这里没有提供相关训练的文件，因为后续上传的时候没找到数据集，只保留了训练好的权重。
 # 数据集的根目录 path: ./datasets/mask-dataset   # 训练数据集的路径 train: images/train   # 验证数据集的路径 val: images/val   # 类别数量 nc: 2   # 类别名称 names: ['unmasked', 'masked']    
可以试一下
